spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aad_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/ddl/01_schema.sql
      data-locations: classpath:sql/ddl/02_procedures.sql, classpath:sql/ddl/03_sample_data.sql
      continue-on-error: false