spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop # Crea las tablas al iniciar y las borra al cerrar [cite: 32]
    show-sql: true
    properties:
      hibernate:
        format_sql: true